# Generated by Django 5.2 on 2025-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distanse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
