# Generated by Django 5.2 on 2025-07-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_run_distanse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='distanse',
            new_name='distance',
        ),
    ]
