# Generated by Django 5.2 on 2025-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_collectibleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
