# Generated by Django 5.2 on 2025-07-25 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_alter_collectibleitem_name_alter_collectibleitem_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='collected_by',
            field=models.ManyToManyField(blank=True, related_name='athlete_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
