# Generated by Django 5.2 on 2025-07-25 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_collectibleitem_collected_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='collected_by',
            field=models.ManyToManyField(blank=True, related_name='collected_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
