# Generated by Django 5.2 on 2025-07-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_alter_collectibleitem_collected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
