# Generated by Django 5.2 on 2025-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_alter_run_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
