# Generated by Django 5.2 on 2025-07-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
