# Generated by Django 5.2 on 2025-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0016_position_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
