# Generated by Django 5.2 on 2025-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_run_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
