# Generated by Django 5.2 on 2025-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0018_alter_position_distance_alter_position_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
