# Generated by Django 5.2 on 2025-08-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subscribe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
