# Generated by Django 5.2 on 2025-08-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0022_subscribe_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscribe',
            new_name='rating',
        ),
    ]
