# Generated by Django 5.2 on 2025-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0023_rename_subscribe_subscribe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
