# Generated by Django 5.2 on 2025-08-06 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_alter_subscribe_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscribe',
            index=models.Index(fields=['athlete'], name='app_run_sub_athlete_c39269_idx'),
        ),
        migrations.AddIndex(
            model_name='subscribe',
            index=models.Index(fields=['coach'], name='app_run_sub_coach_i_bde079_idx'),
        ),
    ]
