# Generated by Django 5.2 on 2025-08-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0025_subscribe_app_run_sub_athlete_c39269_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscribe',
            name='app_run_sub_athlete_c39269_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscribe',
            name='app_run_sub_coach_i_bde079_idx',
        ),
    ]
